# Generated by Django 4.1.3 on 2022-11-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATS_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderstravelinfo',
            name='asset_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
