# Generated by Django 4.1.3 on 2022-11-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATS_api', '0002_riderstravelinfo_asset_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesterhistory',
            name='asset_sensitivity',
            field=models.CharField(choices=[('HIGHLY_SENSITIVE', 'HIGHLY_SENSITIVE'), ('SENSITIVE', 'SENSITIVE'), ('NORMAL', 'NORMAL')], default='NORMAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='requesterhistory',
            name='asset_type',
            field=models.CharField(choices=[('LAPTOP', 'LAPTOP'), ('TRAVEL_BAG', 'TRAVEL_BAG'), ('PACKAGE', 'PACKAGE')], default='PACKAGE', max_length=50),
        ),
        migrations.AlterField(
            model_name='riderstravelinfo',
            name='travel_medium',
            field=models.CharField(choices=[('BUS', 'BUS'), ('CAR', 'CAR'), ('TRAIN', 'TRAIN')], default='CAR', max_length=50),
        ),
    ]
