# Generated by Django 4.1.3 on 2022-11-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATS_api', '0003_alter_requesterhistory_asset_sensitivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesterhistory',
            name='transportation_status',
            field=models.CharField(default='NOT_APPLIED', max_length=50),
        ),
    ]
